asit_center_momentum: 0.9
asit_momentum: 0.996
asit_pretrain_epochs: 100
asit_proj_dim: 256
asit_proj_layers: 3
asit_temperature: 0.07
dropout: 0.0
lr: 0.0001
n_mels: 128
patch_loss_weight: 1.0
patch_size_freq: 16
patch_size_time: 16
time_frames: 313
vit_model: small
warmup_epochs: 10
weight_decay: 1.0e-05
